"use client";

import { ChartLineIcon as ChartLine, ClockCounterClockwiseIcon as ClockCounterClockwise, HouseIcon as House, ListChecksIcon as ListChecks, PackageIcon as Package, WarningCircleIcon as WarningCircle } from "@phosphor-icons/react";
import { useQuery } from "@tanstack/react-query";
import { ActionLink } from "@/components/ui/button";
import { PageHeader } from "@/components/ui/page-header";
import { fetchAnalyticsSummary, fetchOperationsList, fetchRecents } from "@/lib/api";

const metrics = [["active_shipments", "Active shipments", "Cases still in motion"], ["assessments", "New cases", "Created in this period"], ["open_exceptions", "Open exceptions", "Need a documented resolution"], ["overdue_work", "Overdue work", "Past the configured target"], ["release_authorized", "Ready to dispatch", "Awaiting movement confirmation"]] as const;
export default function DashboardPage() {
  const summary = useQuery({ queryKey: ["analytics-summary", 7], queryFn: () => fetchAnalyticsSummary(7), refetchInterval: 30_000 });
  const recents = useQuery({ queryKey: ["recents"], queryFn: fetchRecents });
  const exceptions = useQuery({ queryKey: ["dashboard-exceptions"], queryFn: () => fetchOperationsList("/exceptions", { status: "OPEN" }) });
  if (summary.isPending) return <div className="page-loading">Loading your workspace...</div>;
  if (summary.isError || !summary.data) return <div role="alert" className="notice notice--danger">The workspace summary is not available right now.</div>;
  const data = summary.data;
  const recent = recents.data?.items || [];
  const openExceptions = exceptions.data?.items || [];
  return <div className="operations-page"><PageHeader icon={House} title="Overview" description="A clear view of shipments, exceptions, and decisions that need attention." actions={<ActionLink href="/shipments/new" icon={Package}>Create shipment</ActionLink>} /><section className="metric-grid metric-grid--four" aria-label="Operational summary">{metrics.map(([key, label, description]) => <div className="metric-cell" key={key}><span>{label}</span><strong>{String(data[key] || 0)}</strong><small>{description}</small></div>)}</section><div className="dashboard-grid"><section className="data-panel"><div className="data-panel__header"><div><h2>Work needing attention</h2><p>Open exceptions and assigned work are kept visible until resolved.</p></div><ActionLink href="/work-queue" variant="ghost" icon={ListChecks}>Open queue</ActionLink></div>{openExceptions.length ? <div className="activity-list">{openExceptions.slice(0, 5).map((item) => <a key={String(item.id)} href={`/shipments/${String(item.shipment_id)}`} className="activity-row"><div><strong>{String(item.summary)}</strong><small>{String(item.shipment_reference)} · {String(item.severity)} · {String(item.status)}</small></div><WarningCircle size={18} /></a>)}</div> : <div className="empty-state"><ListChecks size={22} /><strong>No open exceptions</strong><span>New findings will appear here when a shipment needs attention.</span></div>}</section><section className="data-panel"><div className="data-panel__header"><div><h2>Workspace pulse</h2><p>Persisted activity from the last seven days.</p></div><ChartLine size={20} /></div><div className="quality-value"><strong>{String(data.release_authorized || 0)}</strong><span>ready to dispatch</span></div><dl className="definition-list"><div><dt>Active shipments</dt><dd>{String(data.active_shipments || 0)}</dd></div><div><dt>Open exceptions</dt><dd>{String(data.open_exceptions || 0)}</dd></div><div><dt>Overdue work</dt><dd>{String(data.overdue_work || 0)}</dd></div></dl><ActionLink href="/analytics" variant="ghost" icon={ChartLine}>Open analytics</ActionLink></section></div><section className="data-panel data-panel--wide"><div className="data-panel__header"><div><h2>Recently opened</h2><p>Jump back into the records you reviewed most recently.</p></div><ActionLink href="/recents" variant="ghost" icon={ClockCounterClockwise}>View all</ActionLink></div>{recent.length ? <div className="activity-list">{recent.slice(0, 6).map((item) => <a key={`${String(item.object_type)}-${String(item.object_id)}`} href={String(item.href)} className="activity-row"><div><strong>{String(item.label)}</strong><small>{String(item.object_type)} · {new Date(String(item.viewed_at)).toLocaleString("en-GB")}</small></div><ClockCounterClockwise size={17} /></a>)}</div> : <div className="empty-state"><strong>No recent records</strong><span>Open a shipment or workspace setting and it will appear here.</span></div>}</section></div>;
}
