"use client";
import { useQuery } from "@tanstack/react-query";
import { fetchMonitoring } from "@/lib/api";

function State({ value }: { value: string }) { return <span className={`inline-flex items-center gap-2 text-sm ${value === "healthy" ? "text-green-700" : value === "degraded" ? "text-amber-700" : "text-red-700"}`}><span className="h-2 w-2 rounded-full bg-current" />{value}</span>; }
export default function MonitoringPage() {
  const { data, isPending, isError } = useQuery({ queryKey: ["monitoring"], queryFn: fetchMonitoring, refetchInterval: 30_000 });
  if (isPending) return <p className="py-12 text-sm text-[var(--subtle)]">Memuat monitoring…</p>;
  if (isError || !data) return <div role="alert" className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">Monitoring tidak tersedia.</div>;
  return <div><p className="text-xs uppercase tracking-[0.16em] text-[var(--subtle)]">Application signals</p><h1 className="mt-2 text-2xl font-semibold">Monitoring</h1><p className="mt-1 text-sm text-[var(--subtle)]">Sinyal runtime yang tersedia dari aplikasi, bukan observability palsu.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="text-xs text-[var(--subtle)]">Application</div><div className="mt-3"><State value={data.application} /></div></div><div className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="text-xs text-[var(--subtle)]">Database readiness</div><div className="mt-3"><State value={data.database} /></div></div><div className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="text-xs text-[var(--subtle)]">Extraction provider</div><div className="mt-3 font-medium">{data.extraction_provider}</div><div className="mt-1 text-xs text-[var(--subtle)]">{data.provider_configured ? "Configured" : "Not configured"}</div></div><div className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="text-xs text-[var(--subtle)]">Build</div><div className="mt-3 font-medium">v{data.version}</div><div className="mt-1 text-xs capitalize text-[var(--subtle)]">{data.environment}</div></div></div><section className="mt-5 rounded-lg border border-[var(--border)] bg-white p-5"><h2 className="font-semibold">Recent volume</h2><p className="mt-1 text-sm text-[var(--subtle)]">Volume satu hari terakhir dari persisted reconciliation records.</p><dl className="mt-5 grid gap-5 sm:grid-cols-3"><div><dt className="text-xs text-[var(--subtle)]">Processed</dt><dd className="mt-1 text-2xl font-semibold">{String(data.volume.reconciliations_today ?? 0)}</dd></div><div><dt className="text-xs text-[var(--subtle)]">Average latency</dt><dd className="mt-1 text-2xl font-semibold">{Math.round(Number(data.volume.average_processing_ms ?? 0))} ms</dd></div><div><dt className="text-xs text-[var(--subtle)]">HOLD</dt><dd className="mt-1 text-2xl font-semibold">{String(data.volume.hold_today ?? 0)}</dd></div></dl></section></div>;
}
